dependencies:
  build:
    - python:2.7.13

build_targets:
  - name: default
    environment: 
      - SKIPPER_IGNORE=pip install pytest coverage pytest-cov;pip install -r requirements-dev.txt
      - PYTHONPATH=/workspace/tmp
    commands:
      - env
      - apt -y update
      - apt -y install unzip
      - mkdir -p tmp
      - cp /opt/yb/lib/python/yourbase.egg ./tmp
      - unzip tmp/yourbase.egg
      - pip install --upgrade pip
      - pip install -e .[socks]
      - pip install -r requirements-dev.txt
      - pip install urllib3
      - pip install pytest coverage pytest-cov
      - pytest tests --junitxml=report.xml

ci:
  builds:
    - name: default
      build_target: default
